---
version: "3"
services:
 devopsdb:
   image: kopanathisaikrishna/mysecondrepo:dbimage
   ports:
     - "3306:3306"

 application:
   image: kopanathisaikrishna/mysecondrepo:appimage
   ports:
     - "9999:8080"
   depends_on:
     - "devopsdb"
